# Generated by Django 3.2.8 on 2021-12-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organization: ')),
                ('type', models.CharField(max_length=100, verbose_name='Type of organization: ')),
                ('sum_of_students', models.IntegerField(verbose_name='Sum of students: ')),
                ('president', models.CharField(max_length=200, verbose_name='President of the group: ')),
            ],
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name: ')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname: ')),
                ('age', models.IntegerField(verbose_name='Age: ')),
                ('gpa', models.FloatField(verbose_name='GPA: ')),
                ('comment', models.TextField(verbose_name='Comment about university: ')),
            ],
        ),
    ]
